name: test

on: [ push, workflow_dispatch ]

jobs:        
  vz:
    name: "vz"
    runs-on: macos-13
    timeout-minutes: 120
    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: 1.20.x
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Make
      run: make
    - name: Install
      run: make install
    - name: Install test dependencies
      run: brew install qemu bash coreutils
    - name: Cache ~/Library/Caches/lima/download
      uses: actions/cache@v3
      with:
        path: ~/Library/Caches/lima/download
        key: ${{ runner.os }}-vz
    - name: Test
      run: |
        bash --version
        ./hack/test-example.sh examples/experimental/vz.yaml
